builds:
  - binary: goprotoc
    main: ./cmd/goprotoc
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - 386
    ldflags:
      - -s -w -X github.com/jhump/goprotoc/app/goprotoc.version=v{{.Version}}

archive:
  format: tar.gz
  format_overrides:
    - goos: windows
      format: zip
  replacements:
    amd64: x86_64
    386: x86_32
    darwin: osx
  files:
    - LICENSE
